<a href="https://colab.research.google.com/github/Singhananddev/hello-world/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("Gpu is not available.Using CPU.")

GPU is available!
using GPU:Tesla T4


Creating a Tensor

In [5]:
#using empty
a= torch.empty(2,3)

In [6]:
#check type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.4653, 0.1617, 0.5259],
        [0.1652, 0.2496, 0.9890]])

In [10]:
#use of seed
torch.rand(2,3)

tensor([[0.8113, 0.4746, 0.5383],
        [0.4227, 0.4055, 0.6746]])

In [11]:
#manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
#using tensor
torch.tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor Shapes


In [19]:
x= torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[              0,       151757760,       125216320],
        [139736791755344,               0,               0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
#using to ()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
#mathmatical operations